### ISSUE TITLE
Project description lists changejs instead of chance.js

### ISSUE THREAD

**Issue by pyoor** [sunesimonsen/chance-generators#35]
Minor nit but the GitHub project description is listed as:
`Random generators based on changejs`

It should be:
`Random generators based on chance.js`

**Comment by papandreou** [comment]
PR welcome :+1:

**Comment by papandreou** [comment]
Ah, the repo description, can't PR that. @sunesimonsen, I think you're the only one that can fix that :+1:

**Comment by sunesimonsen** [comment]
Thanks I’ll fix it.

**Comment by sunesimonsen** [comment]
Should be fixed now.
