### ISSUE TITLE
Make generator mappers more discoverable

### ISSUE THREAD

**Issue by papandreou** [sunesimonsen/chance-generators#4]
After I've learned about the `map` method of generators I'm slowly realizing that the mapper functions themselves are very powerful, reusable and composable. I feel we should encourage sharing of such functions, and maybe add some of the most useful ones to core.

We might also want to consider changing the API slightly. it always occurred to me as odd that it was OK to use a `Generators` instance declared in an outer scope inside the mapper function body (probably because it looks like a side effect and mapper should be "pure"), for example:

``` js
var g = new Generators(424);
var equallyLongStrings = g.integer({min:0, max: 10}).map(function (n) {
  return g.array(g.string({length: n}));
});
```

Would it be possible to eg. pass the `Generators` instance to the mapper function as the second parameter? I think that would make it easier to put generator mappers into libraries.

**Comment by sunesimonsen** [comment]
I think it is a good idea to provide the generators as the second argument, as it would make it easier to write sharable generators. 

I don't think we can do anything to prevent side-effects happening in the mapper, as soon as you are doing anything random in the mapper, the function is no longer pure.

**Comment by sunesimonsen** [comment]
Then the example would look the following way:

``` js
var { integer } = new Generators(424);
var equallyLongStrings = integer({min:0, max: 10}).map((n, { array, string }) => (
  array(string({length: n}));
));
```

**Comment by papandreou** [comment]
That's pretty badass! Hadn't thought about using destructuring for that.

**Comment by papandreou** [comment]
One thing I forgot about -- if the "equally long strings" mapper were to be added to a library, it might also want to expose options of its own, governing how the fuzzing is done. How would we handle that? The only idea I can come up with would be wrapping the mapper in a function that takes an optional `options` object, and then you'll always call it as a function, express middleware-style:

``` js
var myMapperLib = {
    equallyLongStrings: ({maxArrayLength = 5} = {}) => (n, {array, string}) => array(string({length: n}), maxArrayLength)
};

var { integer } = new Generators(42);
var generator = integer({min:0, max: 10})
  .map(myMapperLib.equallyLongStrings());

var otherGenerator = integer({min:0, max: 10})
  .map(myMapperLib.equallyLongStrings({ maxArrayLength: 10 }));
```

**Comment by sunesimonsen** [comment]
I think your idea of a function that takes arguments makes sense - it is simple and understandable.
